parsers:
  polezznoe:
    name: 'Полезное'
    slug: 'polezznoe'
    settings:
      url: 'https://cloudparser.ru/export/78822-1-1241829632'
      parse_type: 'static'
      encoding: 'windows-1251'
      col_sep: ';'
      short_name: 'pzn'
      category_find_target_column_name: ['Название товара', 'Корневая']
      spreadsheet_sync_url: '1_DhZvlzwlviXWVgksClNF1cNUl-F8e_Z9_-LjY0P-AU'
      categories:
        - nuts: 'орехи'

  urbech:
    name: 'Урбеч'
    slug: 'urbech'
    settings:
      url: 'https://urbech.org/catalog'
      categories_css_path: '.col-right .categories a'
      exclude_categories: ['Новинки', 'Акции',]
      short_name: 'urbch'

  afon:
    name: 'Афоновый сад'
    slug: 'afon'
    settings:
      short_name: 'afon'
      url: 'https://docs.google.com/spreadsheets/d/1L1kUWSc6tCLymAKifgMKbAENJX6MIGt4zusIgRiOV8o/edit#gid=200184738'
      type: 'with_pages'
      pages: ['Масло оливковое', "Оливки, пасты, брускеты", 'Овощная консервация', 'Сладости', 'Макароны, мука', 'Постная трапеза', 'Разное' ]
