parsers:
  polezznoe:
    name: 'Полезное'
    settings:
      url: 'https://cloudparser.ru/export/78822-1-1241829632'
      parse_type: 'static'
      encoding: 'windows-1251'
      col_sep: ';'
      slug: 'pzn'
      category_find_target_column_name: ['Название товара', 'Корневая']
      spreadsheet_sync_url: '1_DhZvlzwlviXWVgksClNF1cNUl-F8e_Z9_-LjY0P-AU'
      categories:
        - nuts: 'орехи'

  urbech:
    name: 'Урбеч'
    settings:
      url: 'https://urbech.org/catalog'
      categories_css_path: '.col-right .categories a'
      exclude_categories: ['Новинки', 'Акции',]

